import type { PhotoItem } from '@nuxt-photo/core'

export const photos: PhotoItem[] = [
  {
    id: 1,
    src: 'https://picsum.photos/seed/nuxt-photo-1/1600/1000',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-1/640/400',
    width: 1600,
    height: 1000,
    alt: 'Desert landscape at golden hour',
    caption: 'Desert Light',
    description: 'Golden hour over sand dunes with long shadows stretching across the landscape.',
  },
  {
    id: 2,
    src: 'https://picsum.photos/seed/nuxt-photo-2/1200/1500',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-2/480/600',
    width: 1200,
    height: 1500,
    alt: 'Ocean waves reflecting light',
    caption: 'Ocean Glass',
    description: 'Crystal clear waves catching the afternoon sunlight along the coast.',
  },
  {
    id: 3,
    src: 'https://picsum.photos/seed/nuxt-photo-3/1600/1067',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-3/640/427',
    width: 1600,
    height: 1067,
    alt: 'Canyon at dusk',
    caption: 'Evening Canyon',
    description: 'Deep canyon walls painted in warm evening hues.',
  },
  {
    id: 4,
    src: 'https://picsum.photos/seed/nuxt-photo-4/1500/1000',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-4/600/400',
    width: 1500,
    height: 1000,
    alt: 'Misty forest',
    caption: 'Forest Haze',
    description: 'Morning fog drifting through ancient trees.',
  },
  {
    id: 5,
    src: 'https://picsum.photos/seed/nuxt-photo-5/1400/1750',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-5/480/600',
    width: 1400,
    height: 1750,
    alt: 'Mountain peak framed by trees',
    caption: 'Alpine Frame',
    description: 'A snow-capped peak framed perfectly by towering pines.',
  },
  {
    id: 6,
    src: 'https://picsum.photos/seed/nuxt-photo-6/1600/1100',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-6/640/440',
    width: 1600,
    height: 1100,
    alt: 'Soft coastal sunset',
    caption: 'Soft Coast',
    description: 'Pastel skies reflecting off calm coastal waters at sunset.',
  },
  {
    id: 7,
    src: 'https://picsum.photos/seed/nuxt-photo-7/1800/1200',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-7/720/480',
    width: 1800,
    height: 1200,
    alt: 'Lavender field under cloudy sky',
    caption: 'Lavender Dreams',
    description: 'Endless rows of lavender stretching toward a dramatic sky.',
  },
  {
    id: 8,
    src: 'https://picsum.photos/seed/nuxt-photo-8/1300/1700',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-8/500/650',
    width: 1300,
    height: 1700,
    alt: 'Waterfall in lush green valley',
    caption: 'Cascade',
    description: 'A hidden waterfall surrounded by vibrant moss and ferns.',
  },
  {
    id: 9,
    src: 'https://picsum.photos/seed/nuxt-photo-9/1600/900',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-9/640/360',
    width: 1600,
    height: 900,
    alt: 'City skyline at twilight',
    caption: 'Urban Glow',
    description: 'The city lights beginning to shimmer as day turns to night.',
  },
  {
    id: 10,
    src: 'https://picsum.photos/seed/nuxt-photo-10/1400/1400',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-10/560/560',
    width: 1400,
    height: 1400,
    alt: 'Autumn leaves close-up',
    caption: 'Amber Detail',
    description: 'Macro shot of autumn leaves with rich amber and crimson tones.',
  },
  {
    id: 11,
    src: 'https://picsum.photos/seed/nuxt-photo-11/1700/1100',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-11/680/440',
    width: 1700,
    height: 1100,
    alt: 'Snowy mountain range',
    caption: 'Winter Ridge',
    description: 'A pristine mountain range blanketed in fresh snow under clear skies.',
  },
  {
    id: 12,
    src: 'https://picsum.photos/seed/nuxt-photo-12/1500/1900',
    thumbSrc: 'https://picsum.photos/seed/nuxt-photo-12/480/608',
    width: 1500,
    height: 1900,
    alt: 'Tall redwood trees',
    caption: 'Giants',
    description: 'Looking up through towering redwoods toward a canopy of green.',
  },
]
