import type { PhotoItem } from '@lupinum/nuxt-photo/app'

function localPhoto(
  id: string,
  width: number,
  height: number,
  alt: string,
  caption: string,
  description: string,
  meta?: Record<string, unknown>,
): PhotoItem {
  return {
    id,
    src: `/photos/${id}.jpg`,
    width,
    height,
    alt,
    caption,
    description,
    meta,
  }
}

export const photos: PhotoItem[] = [
  localPhoto(
    'desert-light',
    1280,
    800,
    'River canyon with moss-covered walls',
    'Moss Canyon',
    'A river cuts through steep canyon walls covered in green moss.',
    { span: 'wide' },
  ),
  localPhoto(
    'ocean-glass',
    960,
    1200,
    'Dandelion seed heads in evening light',
    'Seed Heads',
    'Dandelion clocks catch the low evening sun in a wide meadow.',
  ),
  localPhoto(
    'evening-canyon',
    1280,
    854,
    'Wall covered in open book pages',
    'Paper Wall',
    'Hundreds of open pages pinned side by side into one wall.',
  ),
  localPhoto(
    'forest-haze',
    1200,
    800,
    'Orange tulips at the edge of a forest',
    'Forest Tulips',
    'Orange tulips glow in the soft light between the trees.',
  ),
  localPhoto(
    'alpine-frame',
    960,
    1200,
    'Sea of clouds under a blue sky',
    'Above the Clouds',
    'A layer of clouds stretches to the horizon under a clear sky.',
    { span: 'tall' },
  ),
  localPhoto(
    'soft-coast',
    1280,
    880,
    'Road through tall trees in fog',
    'Fog Road',
    'A quiet road disappears into the fog between tall trees.',
  ),
  localPhoto(
    'lavender-dreams',
    1200,
    800,
    'City skyline at dusk under a dramatic sky',
    'City at Dusk',
    'The skyline lights up under a heavy evening sky.',
    { featured: true },
  ),
  localPhoto(
    'cascade',
    918,
    1200,
    'Bicycle in front of a yellow shopfront',
    'Yellow House',
    'A bicycle rests outside a yellow shopfront under the trees.',
  ),
  localPhoto(
    'urban-glow',
    1280,
    720,
    'Green mountain ridge with a footpath',
    'Green Ridge',
    'A footpath climbs toward a grassy ridge on a clear afternoon.',
  ),
  localPhoto(
    'amber-detail',
    1200,
    1200,
    'Tall grass backlit by the setting sun',
    'Amber Grass',
    'The setting sun shines through tall grass in warm amber tones.',
    { span: '2x2' },
  ),
  localPhoto(
    'winter-ridge',
    1280,
    828,
    'Large stones in a green meadow',
    'Stone Field',
    'Old boulders rest in a meadow under a hazy sky.',
  ),
  localPhoto(
    'giants',
    948,
    1200,
    'Tools and ropes hanging in a workshop',
    'Workshop',
    'Ropes, tools and old wood hang together in a dim workshop.',
  ),
]
