export { default as Photo } from './Photo.vue'
export { default as PhotoGroup } from './PhotoGroup.vue'
export { default as PhotoAlbum } from './PhotoAlbum.vue'
export { default as PhotoCarousel } from './PhotoCarousel.vue'
export { default as Lightbox } from './Lightbox.vue'
